color-identifiers-mode.el

this allows color-identifiers-mode to be used for jsx files

add support for js-jsx-mode & js2-jsx-mode

---

color-identifiers-mode.el

I've been using this for a little while in OCaml and SML buffers.  If you have any suggestions for improving it, please let me know.  I'm not sure if it's kosher for me to use `cc-mode-get-declarations` here.

Add trivial OCaml/SML support

---

color-identifiers-mode.el

When running on a recent version of emacs it appears `evenp` is no longer recognised (probably because namespaces were introduced?)
This fix requires the common lisp library and tweaks the `evenp` call to refer to `cl-evenp`.

Change `evenp` -> `cl-evenp` in Clojure mode code

---

color-identifiers-mode.el

It relies upon font-lock-variable-name-face being set by rust-mode.
Note: the support into rust-mode was added just recently (at
rust-lang/rust-mode#225), so make sure to have
recent enough version (MELPA has already updated the rust-mode).
Signed-off-by: Constantine Kharlamov <Hi-Angel@yandex.ru>

Add rust-mode to supported langs

---

color-identifiers-mode.el

Should fix [the bug reported](https://github.com/ankurdave/color-identifiers-mode/issues/22#issuecomment-69896023) by @roobie *(note: I'm referring to a comment, please don't close whole issue)*.
I also suspect that some modes I have enabled could've triggered re-fontification more often, that would explain why I met the problem more often than other peoples.
v2: changed the branch of the PR so that the time review takes wouldn't inhibit further development.

Do not change colors of already colored variables v2

---

color-identifiers-mode.el

Works around #55 
The function `color-rgb-to-hex` raises an error when negative values are passed, on Git Emacs.
In the default configuration, these negatives seem to be values under 10^-4 when they occur.
Negative RGB components do not make much sense anyway, so I propose a modification to replace them with 0 values.

fix srgb conversion to hex when negative numbers are involved

---

color-identifiers-mode.el

**Change**
- Previously colors when generated using algorithm and there was not custom setting to avoid some color
- Now we can set a custom variable color-identifiers-avoid-faces to avoid certain faces which we believe represent some other meaning in our context
**Issue**
#59

Feature: Customization to set custom faces to be avoided when generating color 

---

README.md
color-identifiers-mode.el

It's usually unwanted to turn off syntax coloring in irrelevant modes, like markdown, html, other markup modes, unsupported langs…
The first 2 patches allows to limit turned off colors to supported modes. It should not cause regressions for those keeping to unset faces globally, because it's basically adding a hook, and a documentation change. I left so far in the commit the link to discussion behind empty string versus nil, I am unsure whether it's worth putting to a comment.
3-rd patch is irrelevant trivia.

Keep colored syntax in unsupported modes

---

color-identifiers-mode.el

`(looking-back)` function has bad performance, which is explicitly documented. So
it's better to limit its use, either in general, or at least to a portion of buffer.
In my tests, search operations on Python buffers resulted in big CPU
load, which I tracked down to `(looking-back)` function. Limiting
the call with beginning of the buffer improved time a lot.
For testing I searched `not_found_message` in `interpetator.py` file of
meson, and measured time of `(color-identifiers:scan-identifiers)`
function.
Before:
(0.000129431 0 0.0)
(0.001869894 0 0.0)
(0.001798768 0 0.0)
(0.001853524 0 0.0)
(0.002508738 0 0.0)
(0.005276375 0 0.0)
(0.004376699 0 0.0)
(0.004512336 0 0.0)
(0.004265427 0 0.0)
(0.008791819 0 0.0)
(0.00790308 0 0.0)
(0.549390703 0 0.0)
(0.330451611 0 0.0)
(0.48631925 0 0.0) …

color-identifiers-mode.el: limit (looking-back) with line beginning

---

color-identifiers-mode.el

This adds support for meson-mode, a mode for Meson build system.
Note that meson-mode has [only recently started assigning a `font-lock-variable-name-face` to variables](https://github.com/wentasah/meson-mode/pull/20).

color-identifiers-mode.el: add support for meson-mode

---

color-identifiers-mode.el

Instead of throwing and catching an exception let's just pre-assign the
variable. It take less code, less indentation, and is faster.

color-identifiers-mode.el: simplify while loop a bit

---

color-identifiers-mode.el

The 1st commit is just a fix to docs. I took me quite some time to figure out why does `(nth 0 color-identifiers:modes-alist)` give me a list where first element is not a regular expression, as opposed to what documentation says. So here's a fix.
The 2nd commit fixes the problem that in Python mode identifiers starting right at the beginning of a line were not getting highlighted.
It turns out, the same regular expression that the 2nd commit fixes was used for many other languages. I guess nobody noticed that because I doubt in langs other than python an identifier happens to be at the beginning of a line too often. Either way, 3rd commit fixes the rest of regexes.

Highlight identifiers on start of line 

---

color-identifiers-mode.el

This function was available since 2013 year, so hopefully this little
cleanup won't hurt anyone.

color-identifiers-mode.el: wire up defvar-local wherever suitable

---

color-identifiers-mode.el

E.g. args in code like
def func(a: int, b: str = None)

color-identifiers-mode.el: python, highlight typed function args

---

README.md

Pinging melpa.milkbox.net says
melpa.milkbox.net: Name or service not known
Looking at the official melpa documentation, they use the other domain
name, so let's use it too.

README.md: melpa domain is changed, fix the broken link

---

color-identifiers-mode.el

First of all, running the hook is automated by the `define-minor-mode`
macro. It creates the hook if it was not yet defined, and always automatically
runs it whenever the mode is enabled.
Second, the "else" branch where the
(run-hooks 'color-identifiers-mode-hook))
code was located in my experiments was never ran. Not upon enabling the
mode, nor upon closing the buffer. I am not sure under what circumstance
it may run, tbh.

color-identifiers-mode.el: don't run hooks manually

---

color-identifiers-mode.el

This fixes #77
I tested it on my computer and it looks good with a cuda file.
To test it yourself, install `cuda-mode` and open a cuda file (ending in `.cu`).  Or just open a c++ file and put it in cuda-mode because c++ and CUDA have nearly identical syntax.

Add cuda-mode to modes-alist

---

color-identifiers-mode.el

As upstream Emacs are discussing possibility of migrating to tree-sitter, I decided to see if color-identifiers mode I use daily supports it.
In this PR, first 2 commits are unrelated fixes. 3rd commit is a small optimization; the variable `color-identifiers:colorize-behavior` it adds will be used in later commits. And finally, last commits introduce tree-sitter support for various languages.
Tree-sitter currently also supports JS, but I see lots of js-related modes in color-identifers and I'm kinda lost which needs to have the `tree-sitter-hl-face:variable` declared. As I don't usually use JS, I left that to the next motivated person to fix.
Note: the tree-sitter changes I only tested in c-mode and python-mode. Any additional testing is more than welcome.

Tree-sitter support

---

README.md
color-identifiers-mode.el

As #27 mentions, there is no documented ability to change recoloring delay to e.g. `0`. Such variable sounds useful to have, so let's add that. With this PR there is a variable `color-identifiers:recoloring-delay` that may be set to any delay a user wants, including zero.
Fixes: https://github.com/ankurdave/color-identifiers-mode/issues/27
Fixes: https://github.com/ankurdave/color-identifiers-mode/issues/75

Add an ability to change recoloring delay

---

README.md
color-identifiers-mode.el

I think, the default delay of 5 seconds is kinda too big. People sometimes even think the mode doesn't work because of  that *(see #27, #75)*.
In real world after adding a variable you want it to be colored as fast as possible. So how about increasing interactivity a bit by decreasing the delay down to 2 seconds?

RFC: Decrease delay before recoloring to improve interactivity

---

color-identifiers-mode.el

As a side note, ts-based modes (mentioned above in particular) [will be supported by Emacs 29 release](https://blog.phundrak.com/emacs-29-what-can-we-expect/).
Screenshot with `tsx-ts-mode` enabled:
As a side note, support for non-tree-sitter typescript mode was added in https://github.com/ankurdave/color-identifiers-mode/pull/74/files , so that is covered since year 2020.
Fixes: https://github.com/ankurdave/color-identifiers-mode/issues/85

Add support for typescript-ts-mode and tsx-ts-mode

---

color-identifiers-mode.el

This allows to get rid of (delete-dups) and slightly improves the overall time. Measured with 1000 identifiers and 100 runs:
Before: 0.1222, 0.1190, 0.1104
After:  0.1068, 0.1121, 0.0779

Convert a few identifiers listing funcs to hash-table

---

color-identifiers-mode.el

`scan-identifiers` isn't the best scan-fn (see also #94) as it moves not
just through changed properties. Let's use the cc-mode one, which goes
exclusively through face changes while searching for declared
identifiers.
Fixes: https://github.com/ankurdave/color-identifiers-mode/issues/40

Use more lightweight cc-mode scanning function for js2-mode

---

color-identifiers-mode.el

`scan-identifiers` isn't the best scan-fn (see also #94) as it moves not just through changed properties. Let's use the cc-mode one, which goes exclusively through face changes while searching for declared identifiers.
Fixes: https://github.com/ankurdave/color-identifiers-mode/issues/62

Use more lightweight cc-mode scanning function for js2-jsx-mode

---

README.md

Using it the way the example suggests will result in harmless warnings in *Messages* buffer, [described here](https://emacs.stackexchange.com/questions/35349/what-is-the-correct-way-to-unset-foreground-color).
Unable to load color ""
As described on the same page, more correct way to drop unwanted highlight would be to inherit the default style in face-remap call.
As a side note, I've been using this "default style remap" for 2 years now with no problems.

README.md: avoid warnings in face-remap example

---

color-identifiers-mode.el

Why?:
- ClojureScript is the same as Clojure - syntax-wise. But ClojureScript has its own major mode in Emacs which is currently preventing color-identifiers-mode from working in .cljs files.
This change addresses the need by:
- Add clojurescript-mode to color-identifiers:modes-alist

feat: Add highlighting for clojurescript files

---

color-identifiers-mode.el

It should be faster and allows to get rid of `delete-dups`

Migrate python-get-declaration to hash-table

---

color-identifiers-mode.el

Major changes:
1. It is transformed from a recursive version to iterative one
2. hash-tables are used now instead of a list
3. As the function is pretty heave since it needs to read the whole buffer, a check for whether input is pending was added

Cleanups and improvements to elisp-mode declarations scanning

---

color-identifiers-mode.el

Do it by interrupting parsing if user is trying to do something.
See also: https://github.com/ankurdave/color-identifiers-mode/issues/103

Alleviate slowness of parsing huge 20k+ lines python files

---

color-identifiers-mode.el

Fixes a bytecompile warning:
⛔ Warning (comp): color-identifiers-mode.el:385:14: Warning: Pattern t is deprecated.  Use `_' instead

Fix bytecompile warning "Pattern t is deprecated.  Use `_' instead"

---

color-identifiers-mode.el

The place where it was used was removed as part of refactorings a few weeks ago, so no reason to keep it.

Remove unused arg from (scan-identifiers)

---

color-identifiers-mode.el

In the same vein as the other tree-sitter mode changes, e.g. #91.  Tested on emacs 30.0.50.

Add rust-ts-mode as a recognized mode

---

color-identifiers-mode.el

It's a no-op change as (font-lock-flush) was doing nothing with font-lock mode disabled anyway. But as we're checking for the mode, let's do so earlier.
I also grepped through local elpa dir, and other packages that do that kind of conditioning work similarly.

Don't call (font-lock-flush) unless font-lock-mode is enabled

---

color-identifiers-mode.el

Apparently, the fact it's declared with `defvar-local` is not enough. Presumably, (make-hash-table) is only executed when the ELisp file gets loaded, but upon further enabling/disabling the mode it's not. So the hash-table is created just once, and re-used every time mode loads. As a result, this "buffer-local" variable implicitly becomes a global one.
Work around that by defaulting the variable to nil and then initializing it inside the mode definition.

Make buffer-local color-index even more buffer-local

---

color-identifiers-mode.el

This fixes a number of native-compilation warnings about variables being undefined.

Define mode after all variables are defined

---

color-identifiers-mode.el
tests.el

A few more warnings has been enabled in latest Emacs, let's fix that

Fix new warnings enabled in upstream

---

.github/workflows/ci.yml
color-identifiers-mode.el

When GUI emacs is used and additionally terminal-based `emacsclient' gets launched, that may cause colors for identifiers change globally. This is not a good user experience. Ideally we should keep two separate vectors, for graphics and terminal versions of colors. But it's unclear how that should communicate with theme changes, so unless there's demand, let's for now just make sure we don't toggle colors back and forth everywhere.

Don't regenerate colors when emacsclient with a different UI appears

---

README.md
build.ninja
color-identifiers-mode.el

I've been always using the plugin with the faces being locally set to `:weight bold`, because to my eye identifiers with the default weight are harder to distinguish. I figure, it may be useful to other people, so decided to implement it in the code.

Support extra face properties on identifiers

---

color-identifiers-mode.el

Most notably, package installation process is known to create one via `with-temp-buffer` and then enable `emacs-lisp-mode` for the purpose of parsing autoloads, which in turn triggers color-identifers-mode for no reason. During a huge upgrade this may add up, especially given our ad hoc ELisp parsing code isn't the fastest.
It also may result in hang due to https://github.com/ankurdave/color-identifiers-mode/issues/84

Avoid turning on the mode in temporary buffers

---

color-identifiers-mode.el

For Emacs 25.1 and higher that makes `(color-identifiers:refontify)` an alias to
`(font-lock-flush)`. `(color-identifiers:refontify)` always was just a wrapper, so no
functional change is intended besides removing the unnecessary indirection.
I haven't found a way to just leave `(if (fboundp … (defalias …)` expression at the
top-level and not cause any byte-compilation errors, so the solution required a
little bit of hackery, but hopefully it should be safe. At least tests are passing
and I haven't found any problems.

Rm extra indirection by making (color-identifiers:refontify) an alias

---

color-identifiers-mode.el

This replaces two `put-text-property` calls with a single add-text-properties. I've been using this change with different programming languages for about an year locally, noticed no problem. So it should be fine.
The other commit is a trivial byte-compilation fix for upstream Emacs.

Put face-spec and color-identifiers:fontfified with a single call

---

color-identifiers-mode.el

typescript-ts-mode in master Emacs added support for highlighting some operations with identifiers via `font-lock-variable-use-face'. Before this commit color-identifiers-mode would mistakenly refuse to highlight these. Fix that by explicitly checking for the face while deciding if we want to highlight text at point.
There's also same commit for s/global/globalized minor-mode taken from https://github.com/ankurdave/color-identifiers-mode/pull/123, because without it CI wouldn't pass byte-compilation.

Don't skip highligting font-lock-variable-use-face

---

color-identifiers-mode.el

Just a minor tweak required to get colour identifiers working for clojure-ts-mode.

Enable color-identifiers for clojure-ts-mode
